# Generated by Django 4.1.5 on 2023-01-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre de Producto"),
        ),
    ]
