# Generated by Django 4.1.5 on 2023-01-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="foto",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Imagen del Producto"
            ),
        ),
    ]
